### ISSUE TITLE
Use of function-signatures in completion-signature design may not preserve types

### ISSUE THREAD

**Issue by lewissbaker** [brycelelbach/wg21_p2300_execution#5]
It was mentioned during LWG review that the use of function signatures to represent completion signals may have unintended consequences due to function signatures decaying types to other types, so the function signature you get is not always the same signature you wrote. e.g. writing `set_value_t(T[])` will actually be decayed to `set_value_t(T*)`.

We should either convince ourselves that this decaying is benign for our use-cases, and if so then add the reasoning to the paper, or we should consider an alternative mechanism for representing the signals.

**Comment by ericniebler** [comment]
Some additional context:

1. `set_value_t(T[])` is a bug. Senders have to accurately report what they send. There are no prvalue arrays of unknown size. And `set_value_t(T[5])` says the sender sends a prvalue of an array of five `T`'s which is somewhat implausible.
2. Idiomatically, `set_value` customizations take values by forwarding reference, and when they need to store them somewhere, they store the `std::decay`-ed type of the value anyway.

That said, I could indeed write a sender that sends a prvalue C-style array and tries to claim as such in the completion signatures, where the array type inadvertently decays to a pointer. I could chain this sender to `stdexec::then` passing a callable with `operator()` overloaded: one takes a `T*` and the other takes a `T(&&)[N]`. Those two overloads may return completely different types, let's say `X` and `Y`.

If you ask the composite sender what type it will send, it will say `X`. But the final receiver will actually receive a `Y`.

How worried am I about that? Not terribly. It seems unlikely. The problem was a bit more serious for `std::result_of` because that was an end user-facing utility. In contrast, I don't expect large swaths of C++ programmers to be computing and consuming sender completion signatures.

**Comment by ericniebler** [comment]
this issue is long since settled
